; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "GLPI Agent Watchdog"
#define MyAppVersion "0.4"
#define MyAppPublisher "ra1qcw"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D8D06B80-1D92-461E-B631-33126D5159C2}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
;DefaultDirName="C:\Program Files\GLPI-Agent\agent-wd"\{#MyAppName}
DefaultDirName="C:\Program Files\GLPI-Agent\agent-wd-svc"
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=D:\GLPI-Agent-WD-svc\setup
OutputBaseFilename=awd-setup
Compression=lzma
CloseApplications=yes
SolidCompression=yes
WizardStyle=modern
RestartApplications=yes
RestartIfNeededByRun=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"


[Files]
Source: "D:\GLPI-Agent-WD-svc\agent-wd-svc.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GLPI-Agent-WD-svc\restart-service.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\GLPI-Agent-WD-svc\api-ms-win-core-path-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "D:\GLPI-Agent-WD-svc\"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

[Run]
Filename: "sc"; Parameters: "stop glpi-agent-wd"; Flags: runhidden
Filename: "sc"; Parameters: "delete glpi-agent-wd"; Flags: runhidden
Filename: "{app}\agent-wd-svc.exe"; Parameters: "install"; Flags: runhidden
Filename: "sc"; Parameters: "start glpi-agent-wd"; Flags: runhidden

[UninstallRun]
Filename: "net"; Parameters: "stop glpi-agent-wd";  Flags: runhidden
Filename: "sc"; Parameters: "delete glpi-agent-wd";  Flags: runhidden
